# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frame.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_frame(object):
    def setupUi(self, frame):
        frame.setObjectName("frame")
        frame.resize(1100, 700)
        frame.setMinimumSize(QtCore.QSize(1100, 700))
        frame.setMaximumSize(QtCore.QSize(1100, 700))
        frame.setStyleSheet("QWidget {\n"
"    background-color: #F9F5F6;\n"
"}")
        self.des = QtWidgets.QRadioButton(frame)
        self.des.setGeometry(QtCore.QRect(40, 90, 95, 20))
        self.des.setStyleSheet("QRadioButton {\n"
"    color: #FF7D7D;\n"
"}\n"
"\n"
"QRadioButton::indicator {\n"
"    color: #FF7D7D;\n"
"}\n"
"\n"
"\n"
"")
        self.des.setObjectName("des")
        self.aes = QtWidgets.QRadioButton(frame)
        self.aes.setGeometry(QtCore.QRect(150, 90, 95, 20))
        self.aes.setStyleSheet("QRadioButton {\n"
"    color: #FF7D7D;\n"
"}\n"
"")
        self.aes.setObjectName("aes")
        self.rsa = QtWidgets.QRadioButton(frame)
        self.rsa.setGeometry(QtCore.QRect(260, 90, 95, 20))
        self.rsa.setStyleSheet("QRadioButton {\n"
"    color: #FF7D7D;\n"
"}\n"
"")
        self.rsa.setObjectName("rsa")
        self.textIn = QtWidgets.QTextEdit(frame)
        self.textIn.setGeometry(QtCore.QRect(40, 130, 461, 511))
        self.textIn.setStyleSheet("QTextEdit {\n"
"    border: 1px solid #FF7D7D;\n"
"}\n"
"")
        self.textIn.setObjectName("textIn")
        self.textOut = QtWidgets.QTextEdit(frame)
        self.textOut.setGeometry(QtCore.QRect(600, 130, 461, 511))
        self.textOut.setStyleSheet("QTextEdit {\n"
"    border: 1px solid #FF7D7D;\n"
"}\n"
"")
        self.textOut.setReadOnly(True)
        self.textOut.setObjectName("textOut")
        self.encrypt = QtWidgets.QPushButton(frame)
        self.encrypt.setGeometry(QtCore.QRect(830, 80, 93, 28))
        self.encrypt.setStyleSheet("QPushButton {\n"
"    background-color: #F8C4B4;\n"
"    border: none;\n"
"    color: #FF6464;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: palette(light);\n"
"}")
        self.encrypt.setObjectName("encrypt")
        self.decrypt = QtWidgets.QPushButton(frame)
        self.decrypt.setGeometry(QtCore.QRect(970, 80, 93, 28))
        self.decrypt.setStyleSheet("QPushButton {\n"
"    background-color: #F8C4B4;\n"
"    border: none;\n"
"    color: #FF6464;\n"
"}\n"
"QPushButton:hover {\n"
"    color: palette(light);\n"
"}")
        self.decrypt.setObjectName("decrypt")
        self.text = QtWidgets.QLabel(frame)
        self.text.setGeometry(QtCore.QRect(40, 60, 171, 16))
        self.text.setStyleSheet("QLabel {\n"
"    color: #FF7D7D;\n"
"}\n"
"")
        self.text.setObjectName("text")

        self.retranslateUi(frame)
        QtCore.QMetaObject.connectSlotsByName(frame)

    def retranslateUi(self, frame):
        _translate = QtCore.QCoreApplication.translate
        frame.setWindowTitle(_translate("frame", "Form"))
        self.des.setText(_translate("frame", "DES"))
        self.aes.setText(_translate("frame", "AES"))
        self.rsa.setText(_translate("frame", "RSA"))
        self.encrypt.setText(_translate("frame", "Encrypt"))
        self.decrypt.setText(_translate("frame", "Decrypt"))
        self.text.setText(_translate("frame", "Please select an algorithm:"))
